### ISSUE TITLE
Add code coverage workflow

### ISSUE THREAD

**Issue by stephprince** [NeurodataWithoutBorders/aqnwb#70]
There is an existing`coverage.cmake` file in the cmake folder. A coverage workflow could look something like this, but I haven't had a chance to test or integrate with codecov yet.

```
coverage:
  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4

  - name: Install LCov
    run: sudo apt-get update -q
      && sudo apt-get install lcov -q -y

  - name: Configure
    run: cmake --preset=ci-coverage

  - name: Build
    run: cmake --build build/coverage -j 2

  - name: Test
    working-directory: build/coverage
    run: ctest --output-on-failure --no-tests=error -j 2

  - name: Process coverage info
    run: cmake --build build/coverage -t coverage

  - name: Submit to codecov.io
    uses: codecov/codecov-action@v4
    with:
      file: build/coverage/coverage.info
      token: ${{ secrets.CODECOV_TOKEN }}
```
